### ISSUE TITLE
add issue_template.md

### ISSUE THREAD

**Issue by championshuttler** [web-ext-labs/ui-tool#24]

**Comment by arshadkazmi42** [comment]
I can take this up. if its still avaialble.
Do you have any template defined?

**Comment by championshuttler** [comment]
Hey @arshadkazmi42 , thanks for offering , feel free to work on it.

**Comment by championshuttler** [comment]
Sorry its already done in https://github.com/web-ext-labs/ui-tool/commit/31d42804792f9025a0a923c6ab02803731be0a48. Closing it.
