### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by championshuttler** [web-ext-labs/ui-tool#25]
Few changes we need to do before 5th Jan 2019 > 

1. Add a line below the WEBEXTENSIONS something like `Scaffolding tool for browser extensions` or soemthing better like `Boilerplate for your browser extensions` or `Build yourself a browser extension in 15 sec` :P 

2. Lets change button to `Lets create for "Firefox Icon"`

3. Remove the Mozilla logo from left side of the toolbar and lets replace it with the `Site is licensed under GPL 3.0` or any better license. 

4. Lets add a credit section on right side of the footer before the `Developer Resources` and that will be linked to README#contibutors section of this repo(need to add ) or we can link it to https://github.com/orgs/web-ext-labs/people . Second option sounds good to me. @tsl143 could you please make this org public on your profile, @tushararora you too. RN it is private.
![image](https://user-images.githubusercontent.com/22130317/50548958-22734080-0c7b-11e9-9293-331514d63890.png)

5. [OPTIONAL] Lets add a mozilla addons icon above `WEBEXTENSIONS`.

cc @tsl143 @tushararora

**Comment by rbrishabh** [comment]
I would like to take up this one!

**Comment by championshuttler** [comment]
@rbrishabh that's great , pick anyone of them and create a pull request for it . I am going to split this bug into separate issues for multiple contributors , for now you can choose anyone of them .

**Comment by suhailsinghbains** [comment]
Hi, can I please solve 2nd bug of this comment.

**Comment by championshuttler** [comment]
@suhailsinghbains Sure!!

**Comment by tsl143** [comment]
>     4\. Lets add a credit section on right side of the footer before the `Developer Resources` and that will be linked to README#contibutors section of this repo(need to add ) or we can link it to https://github.com/orgs/web-ext-labs/people . Second option sounds good to me. @tsl143 could you please make this org public on your profile, @tushararora you too. RN it is private.

I think this is unnecessary, github repo has list of contributors, why duplicate

**Comment by tsl143** [comment]
I really like the non-cluttered UI of the website.
Lets think of minimalist elements.
@championshuttler

**Comment by championshuttler** [comment]
Closing for now. We decided to make no changes in team meeting!. Happy New Year!!

Thanks to all for showing interest in working!!
