### ISSUE TITLE
[Fix it] Domain webextensions.in is down/parked

### ISSUE THREAD

**Issue by actualben** [web-ext-labs/ui-tool#52]
**Describe the bug**
[webextensions.in](http://webextensions.in/) appears to be parked at a domain squatter.

**To Reproduce**
1. visit [webextensions.in](http://webextensions.in/)
2. see offer to "buy this domain"

**Expected behavior**
Valid domain used

**Something else you want us to know**
mozilla/extension-workshop links to this heavily

Can you park this under github.io instead?

**Comment by championshuttler** [comment]
Thanks on it @actualben

**Comment by championshuttler** [comment]
@actualben its hosted now on webext.eu as someone parked the domain as you mentioned. Thanks for filing the bug really appreciate it. 💯
